version: '3.8'

services:
  # 1. SERVİS: PostgreSQL Veritabanı
  db:
    image: postgres:15-alpine
    container_name: staj_db
    restart: always
    environment:
      POSTGRES_DB: stajdb
      POSTGRES_USER: stajuser
      POSTGRES_PASSWORD: stajpass
    ports:
      - "5432:5432"
    volumes:
      # Veritabanı dosyalarının konteyner silinse bile kaybolmaması için kalıcı hacim (Volume) tanımlıyoruz
      - pgdata:/var/lib/postgresql/data

  # 2. SERVİS: Bizim Java Uygulamamız
  staj_app:
    # Dockerfile dosyasını bulunduğumuz dizinde bulup otomatik build edecek
    build: .
    container_name: staj_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      # Sunucumuzdaki /data klasörünü konteyner içindeki /app/data klasörüne bağlıyoruz (Volume Köprüsü)
      - ./data:/app/data

  zabbix-db:
    image: postgres:15-alpine
    container_name: zabbix_db
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_sifre
      - POSTGRES_DB=zabbix
    volumes:
      - zabbix_data:/var/lib/postgresql/data
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix_server
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_sifre
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-db
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix_web
    ports:
      - "8081:8080" # Zabbix paneline 8081 portundan gireceğiz ki uygulamanla çakışmasın
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_sifre
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Istanbul
    depends_on:
      - zabbix-server
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix_agent
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
    restart: always
    privileged: true
    pid: "host"
volumes:
  pgdata:
  zabbix_data:
